// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: obu_service.proto

#include "obu_service.pb.h"
#include "obu_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace grpc {
namespace obu {
namespace msg {

static const char* ObuService_method_names[] = {
  "/grpc.obu.msg.ObuService/answerMethod",
};

std::unique_ptr< ObuService::Stub> ObuService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ObuService::Stub> stub(new ObuService::Stub(channel, options));
  return stub;
}

ObuService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_answerMethod_(ObuService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ObuService::Stub::answerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::obu::msg::ObuAnswerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::grpc::obu::msg::ObuAnswerRequest, ::grpc::obu::msg::ObuAnswerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_answerMethod_, context, request, response);
}

void ObuService::Stub::async::answerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest* request, ::grpc::obu::msg::ObuAnswerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::grpc::obu::msg::ObuAnswerRequest, ::grpc::obu::msg::ObuAnswerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_answerMethod_, context, request, response, std::move(f));
}

void ObuService::Stub::async::answerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest* request, ::grpc::obu::msg::ObuAnswerResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_answerMethod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::grpc::obu::msg::ObuAnswerResponse>* ObuService::Stub::PrepareAsyncanswerMethodRaw(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::grpc::obu::msg::ObuAnswerResponse, ::grpc::obu::msg::ObuAnswerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_answerMethod_, context, request);
}

::grpc::ClientAsyncResponseReader< ::grpc::obu::msg::ObuAnswerResponse>* ObuService::Stub::AsyncanswerMethodRaw(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncanswerMethodRaw(context, request, cq);
  result->StartCall();
  return result;
}

ObuService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ObuService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ObuService::Service, ::grpc::obu::msg::ObuAnswerRequest, ::grpc::obu::msg::ObuAnswerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ObuService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::grpc::obu::msg::ObuAnswerRequest* req,
             ::grpc::obu::msg::ObuAnswerResponse* resp) {
               return service->answerMethod(ctx, req, resp);
             }, this)));
}

ObuService::Service::~Service() {
}

::grpc::Status ObuService::Service::answerMethod(::grpc::ServerContext* context, const ::grpc::obu::msg::ObuAnswerRequest* request, ::grpc::obu::msg::ObuAnswerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpc
}  // namespace obu
}  // namespace msg

