// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obu_service.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_obu_5fservice_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_obu_5fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "obu_message.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_obu_5fservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_obu_5fservice_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_obu_5fservice_2eproto;
namespace grpc {
namespace obu {
namespace msg {
class ObuAnswerRequest;
struct ObuAnswerRequestDefaultTypeInternal;
extern ObuAnswerRequestDefaultTypeInternal _ObuAnswerRequest_default_instance_;
class ObuAnswerResponse;
struct ObuAnswerResponseDefaultTypeInternal;
extern ObuAnswerResponseDefaultTypeInternal _ObuAnswerResponse_default_instance_;
}  // namespace msg
}  // namespace obu
}  // namespace grpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace grpc {
namespace obu {
namespace msg {

// ===================================================================


// -------------------------------------------------------------------

class ObuAnswerRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:grpc.obu.msg.ObuAnswerRequest) */ {
 public:
  inline ObuAnswerRequest() : ObuAnswerRequest(nullptr) {}
  ~ObuAnswerRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ObuAnswerRequest(::google::protobuf::internal::ConstantInitialized);

  inline ObuAnswerRequest(const ObuAnswerRequest& from)
      : ObuAnswerRequest(nullptr, from) {}
  ObuAnswerRequest(ObuAnswerRequest&& from) noexcept
    : ObuAnswerRequest() {
    *this = ::std::move(from);
  }

  inline ObuAnswerRequest& operator=(const ObuAnswerRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObuAnswerRequest& operator=(ObuAnswerRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObuAnswerRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObuAnswerRequest* internal_default_instance() {
    return reinterpret_cast<const ObuAnswerRequest*>(
               &_ObuAnswerRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ObuAnswerRequest& a, ObuAnswerRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ObuAnswerRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObuAnswerRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObuAnswerRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ObuAnswerRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ObuAnswerRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ObuAnswerRequest& from) {
    ObuAnswerRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ObuAnswerRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "grpc.obu.msg.ObuAnswerRequest";
  }
  protected:
  explicit ObuAnswerRequest(::google::protobuf::Arena* arena);
  ObuAnswerRequest(::google::protobuf::Arena* arena, const ObuAnswerRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApiVersionFieldNumber = 1,
  };
  // string api_version = 1;
  void clear_api_version() ;
  const std::string& api_version() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_api_version(Arg_&& arg, Args_... args);
  std::string* mutable_api_version();
  PROTOBUF_NODISCARD std::string* release_api_version();
  void set_allocated_api_version(std::string* value);

  private:
  const std::string& _internal_api_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_api_version(
      const std::string& value);
  std::string* _internal_mutable_api_version();

  public:
  // @@protoc_insertion_point(class_scope:grpc.obu.msg.ObuAnswerRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      49, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr api_version_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_obu_5fservice_2eproto;
};// -------------------------------------------------------------------

class ObuAnswerResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:grpc.obu.msg.ObuAnswerResponse) */ {
 public:
  inline ObuAnswerResponse() : ObuAnswerResponse(nullptr) {}
  ~ObuAnswerResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ObuAnswerResponse(::google::protobuf::internal::ConstantInitialized);

  inline ObuAnswerResponse(const ObuAnswerResponse& from)
      : ObuAnswerResponse(nullptr, from) {}
  ObuAnswerResponse(ObuAnswerResponse&& from) noexcept
    : ObuAnswerResponse() {
    *this = ::std::move(from);
  }

  inline ObuAnswerResponse& operator=(const ObuAnswerResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObuAnswerResponse& operator=(ObuAnswerResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObuAnswerResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObuAnswerResponse* internal_default_instance() {
    return reinterpret_cast<const ObuAnswerResponse*>(
               &_ObuAnswerResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ObuAnswerResponse& a, ObuAnswerResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ObuAnswerResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObuAnswerResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObuAnswerResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ObuAnswerResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ObuAnswerResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ObuAnswerResponse& from) {
    ObuAnswerResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ObuAnswerResponse* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "grpc.obu.msg.ObuAnswerResponse";
  }
  protected:
  explicit ObuAnswerResponse(::google::protobuf::Arena* arena);
  ObuAnswerResponse(::google::protobuf::Arena* arena, const ObuAnswerResponse& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApiVersionFieldNumber = 1,
    kBasicInfoFieldNumber = 2,
    kTrafficLightInfoFieldNumber = 3,
    kWarningInfoFieldNumber = 4,
  };
  // string api_version = 1;
  void clear_api_version() ;
  const std::string& api_version() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_api_version(Arg_&& arg, Args_... args);
  std::string* mutable_api_version();
  PROTOBUF_NODISCARD std::string* release_api_version();
  void set_allocated_api_version(std::string* value);

  private:
  const std::string& _internal_api_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_api_version(
      const std::string& value);
  std::string* _internal_mutable_api_version();

  public:
  // .grpc.obu.msg.ObuBasicInfo basic_info = 2;
  bool has_basic_info() const;
  void clear_basic_info() ;
  const ::grpc::obu::msg::ObuBasicInfo& basic_info() const;
  PROTOBUF_NODISCARD ::grpc::obu::msg::ObuBasicInfo* release_basic_info();
  ::grpc::obu::msg::ObuBasicInfo* mutable_basic_info();
  void set_allocated_basic_info(::grpc::obu::msg::ObuBasicInfo* value);
  void unsafe_arena_set_allocated_basic_info(::grpc::obu::msg::ObuBasicInfo* value);
  ::grpc::obu::msg::ObuBasicInfo* unsafe_arena_release_basic_info();

  private:
  const ::grpc::obu::msg::ObuBasicInfo& _internal_basic_info() const;
  ::grpc::obu::msg::ObuBasicInfo* _internal_mutable_basic_info();

  public:
  // .grpc.obu.msg.ObuTrafficLightInfo traffic_light_info = 3;
  bool has_traffic_light_info() const;
  void clear_traffic_light_info() ;
  const ::grpc::obu::msg::ObuTrafficLightInfo& traffic_light_info() const;
  PROTOBUF_NODISCARD ::grpc::obu::msg::ObuTrafficLightInfo* release_traffic_light_info();
  ::grpc::obu::msg::ObuTrafficLightInfo* mutable_traffic_light_info();
  void set_allocated_traffic_light_info(::grpc::obu::msg::ObuTrafficLightInfo* value);
  void unsafe_arena_set_allocated_traffic_light_info(::grpc::obu::msg::ObuTrafficLightInfo* value);
  ::grpc::obu::msg::ObuTrafficLightInfo* unsafe_arena_release_traffic_light_info();

  private:
  const ::grpc::obu::msg::ObuTrafficLightInfo& _internal_traffic_light_info() const;
  ::grpc::obu::msg::ObuTrafficLightInfo* _internal_mutable_traffic_light_info();

  public:
  // .grpc.obu.msg.ObuWarningInfo warning_info = 4;
  bool has_warning_info() const;
  void clear_warning_info() ;
  const ::grpc::obu::msg::ObuWarningInfo& warning_info() const;
  PROTOBUF_NODISCARD ::grpc::obu::msg::ObuWarningInfo* release_warning_info();
  ::grpc::obu::msg::ObuWarningInfo* mutable_warning_info();
  void set_allocated_warning_info(::grpc::obu::msg::ObuWarningInfo* value);
  void unsafe_arena_set_allocated_warning_info(::grpc::obu::msg::ObuWarningInfo* value);
  ::grpc::obu::msg::ObuWarningInfo* unsafe_arena_release_warning_info();

  private:
  const ::grpc::obu::msg::ObuWarningInfo& _internal_warning_info() const;
  ::grpc::obu::msg::ObuWarningInfo* _internal_mutable_warning_info();

  public:
  // @@protoc_insertion_point(class_scope:grpc.obu.msg.ObuAnswerResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 3,
      50, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr api_version_;
    ::grpc::obu::msg::ObuBasicInfo* basic_info_;
    ::grpc::obu::msg::ObuTrafficLightInfo* traffic_light_info_;
    ::grpc::obu::msg::ObuWarningInfo* warning_info_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_obu_5fservice_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ObuAnswerRequest

// string api_version = 1;
inline void ObuAnswerRequest::clear_api_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.api_version_.ClearToEmpty();
}
inline const std::string& ObuAnswerRequest::api_version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpc.obu.msg.ObuAnswerRequest.api_version)
  return _internal_api_version();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ObuAnswerRequest::set_api_version(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.api_version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpc.obu.msg.ObuAnswerRequest.api_version)
}
inline std::string* ObuAnswerRequest::mutable_api_version() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_api_version();
  // @@protoc_insertion_point(field_mutable:grpc.obu.msg.ObuAnswerRequest.api_version)
  return _s;
}
inline const std::string& ObuAnswerRequest::_internal_api_version() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.api_version_.Get();
}
inline void ObuAnswerRequest::_internal_set_api_version(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.api_version_.Set(value, GetArena());
}
inline std::string* ObuAnswerRequest::_internal_mutable_api_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.api_version_.Mutable( GetArena());
}
inline std::string* ObuAnswerRequest::release_api_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:grpc.obu.msg.ObuAnswerRequest.api_version)
  return _impl_.api_version_.Release();
}
inline void ObuAnswerRequest::set_allocated_api_version(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.api_version_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.api_version_.IsDefault()) {
          _impl_.api_version_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:grpc.obu.msg.ObuAnswerRequest.api_version)
}

// -------------------------------------------------------------------

// ObuAnswerResponse

// string api_version = 1;
inline void ObuAnswerResponse::clear_api_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.api_version_.ClearToEmpty();
}
inline const std::string& ObuAnswerResponse::api_version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpc.obu.msg.ObuAnswerResponse.api_version)
  return _internal_api_version();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ObuAnswerResponse::set_api_version(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.api_version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpc.obu.msg.ObuAnswerResponse.api_version)
}
inline std::string* ObuAnswerResponse::mutable_api_version() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_api_version();
  // @@protoc_insertion_point(field_mutable:grpc.obu.msg.ObuAnswerResponse.api_version)
  return _s;
}
inline const std::string& ObuAnswerResponse::_internal_api_version() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.api_version_.Get();
}
inline void ObuAnswerResponse::_internal_set_api_version(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.api_version_.Set(value, GetArena());
}
inline std::string* ObuAnswerResponse::_internal_mutable_api_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.api_version_.Mutable( GetArena());
}
inline std::string* ObuAnswerResponse::release_api_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:grpc.obu.msg.ObuAnswerResponse.api_version)
  return _impl_.api_version_.Release();
}
inline void ObuAnswerResponse::set_allocated_api_version(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.api_version_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.api_version_.IsDefault()) {
          _impl_.api_version_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:grpc.obu.msg.ObuAnswerResponse.api_version)
}

// .grpc.obu.msg.ObuBasicInfo basic_info = 2;
inline bool ObuAnswerResponse::has_basic_info() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.basic_info_ != nullptr);
  return value;
}
inline const ::grpc::obu::msg::ObuBasicInfo& ObuAnswerResponse::_internal_basic_info() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::grpc::obu::msg::ObuBasicInfo* p = _impl_.basic_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::grpc::obu::msg::ObuBasicInfo&>(::grpc::obu::msg::_ObuBasicInfo_default_instance_);
}
inline const ::grpc::obu::msg::ObuBasicInfo& ObuAnswerResponse::basic_info() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpc.obu.msg.ObuAnswerResponse.basic_info)
  return _internal_basic_info();
}
inline void ObuAnswerResponse::unsafe_arena_set_allocated_basic_info(::grpc::obu::msg::ObuBasicInfo* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.basic_info_);
  }
  _impl_.basic_info_ = reinterpret_cast<::grpc::obu::msg::ObuBasicInfo*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:grpc.obu.msg.ObuAnswerResponse.basic_info)
}
inline ::grpc::obu::msg::ObuBasicInfo* ObuAnswerResponse::release_basic_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::grpc::obu::msg::ObuBasicInfo* released = _impl_.basic_info_;
  _impl_.basic_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::grpc::obu::msg::ObuBasicInfo* ObuAnswerResponse::unsafe_arena_release_basic_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:grpc.obu.msg.ObuAnswerResponse.basic_info)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::grpc::obu::msg::ObuBasicInfo* temp = _impl_.basic_info_;
  _impl_.basic_info_ = nullptr;
  return temp;
}
inline ::grpc::obu::msg::ObuBasicInfo* ObuAnswerResponse::_internal_mutable_basic_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.basic_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::grpc::obu::msg::ObuBasicInfo>(GetArena());
    _impl_.basic_info_ = reinterpret_cast<::grpc::obu::msg::ObuBasicInfo*>(p);
  }
  return _impl_.basic_info_;
}
inline ::grpc::obu::msg::ObuBasicInfo* ObuAnswerResponse::mutable_basic_info() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::grpc::obu::msg::ObuBasicInfo* _msg = _internal_mutable_basic_info();
  // @@protoc_insertion_point(field_mutable:grpc.obu.msg.ObuAnswerResponse.basic_info)
  return _msg;
}
inline void ObuAnswerResponse::set_allocated_basic_info(::grpc::obu::msg::ObuBasicInfo* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.basic_info_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.basic_info_ = reinterpret_cast<::grpc::obu::msg::ObuBasicInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:grpc.obu.msg.ObuAnswerResponse.basic_info)
}

// .grpc.obu.msg.ObuTrafficLightInfo traffic_light_info = 3;
inline bool ObuAnswerResponse::has_traffic_light_info() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.traffic_light_info_ != nullptr);
  return value;
}
inline const ::grpc::obu::msg::ObuTrafficLightInfo& ObuAnswerResponse::_internal_traffic_light_info() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::grpc::obu::msg::ObuTrafficLightInfo* p = _impl_.traffic_light_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::grpc::obu::msg::ObuTrafficLightInfo&>(::grpc::obu::msg::_ObuTrafficLightInfo_default_instance_);
}
inline const ::grpc::obu::msg::ObuTrafficLightInfo& ObuAnswerResponse::traffic_light_info() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpc.obu.msg.ObuAnswerResponse.traffic_light_info)
  return _internal_traffic_light_info();
}
inline void ObuAnswerResponse::unsafe_arena_set_allocated_traffic_light_info(::grpc::obu::msg::ObuTrafficLightInfo* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.traffic_light_info_);
  }
  _impl_.traffic_light_info_ = reinterpret_cast<::grpc::obu::msg::ObuTrafficLightInfo*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:grpc.obu.msg.ObuAnswerResponse.traffic_light_info)
}
inline ::grpc::obu::msg::ObuTrafficLightInfo* ObuAnswerResponse::release_traffic_light_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::grpc::obu::msg::ObuTrafficLightInfo* released = _impl_.traffic_light_info_;
  _impl_.traffic_light_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::grpc::obu::msg::ObuTrafficLightInfo* ObuAnswerResponse::unsafe_arena_release_traffic_light_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:grpc.obu.msg.ObuAnswerResponse.traffic_light_info)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::grpc::obu::msg::ObuTrafficLightInfo* temp = _impl_.traffic_light_info_;
  _impl_.traffic_light_info_ = nullptr;
  return temp;
}
inline ::grpc::obu::msg::ObuTrafficLightInfo* ObuAnswerResponse::_internal_mutable_traffic_light_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.traffic_light_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::grpc::obu::msg::ObuTrafficLightInfo>(GetArena());
    _impl_.traffic_light_info_ = reinterpret_cast<::grpc::obu::msg::ObuTrafficLightInfo*>(p);
  }
  return _impl_.traffic_light_info_;
}
inline ::grpc::obu::msg::ObuTrafficLightInfo* ObuAnswerResponse::mutable_traffic_light_info() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::grpc::obu::msg::ObuTrafficLightInfo* _msg = _internal_mutable_traffic_light_info();
  // @@protoc_insertion_point(field_mutable:grpc.obu.msg.ObuAnswerResponse.traffic_light_info)
  return _msg;
}
inline void ObuAnswerResponse::set_allocated_traffic_light_info(::grpc::obu::msg::ObuTrafficLightInfo* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.traffic_light_info_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.traffic_light_info_ = reinterpret_cast<::grpc::obu::msg::ObuTrafficLightInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:grpc.obu.msg.ObuAnswerResponse.traffic_light_info)
}

// .grpc.obu.msg.ObuWarningInfo warning_info = 4;
inline bool ObuAnswerResponse::has_warning_info() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.warning_info_ != nullptr);
  return value;
}
inline const ::grpc::obu::msg::ObuWarningInfo& ObuAnswerResponse::_internal_warning_info() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::grpc::obu::msg::ObuWarningInfo* p = _impl_.warning_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::grpc::obu::msg::ObuWarningInfo&>(::grpc::obu::msg::_ObuWarningInfo_default_instance_);
}
inline const ::grpc::obu::msg::ObuWarningInfo& ObuAnswerResponse::warning_info() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpc.obu.msg.ObuAnswerResponse.warning_info)
  return _internal_warning_info();
}
inline void ObuAnswerResponse::unsafe_arena_set_allocated_warning_info(::grpc::obu::msg::ObuWarningInfo* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.warning_info_);
  }
  _impl_.warning_info_ = reinterpret_cast<::grpc::obu::msg::ObuWarningInfo*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:grpc.obu.msg.ObuAnswerResponse.warning_info)
}
inline ::grpc::obu::msg::ObuWarningInfo* ObuAnswerResponse::release_warning_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::grpc::obu::msg::ObuWarningInfo* released = _impl_.warning_info_;
  _impl_.warning_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::grpc::obu::msg::ObuWarningInfo* ObuAnswerResponse::unsafe_arena_release_warning_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:grpc.obu.msg.ObuAnswerResponse.warning_info)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::grpc::obu::msg::ObuWarningInfo* temp = _impl_.warning_info_;
  _impl_.warning_info_ = nullptr;
  return temp;
}
inline ::grpc::obu::msg::ObuWarningInfo* ObuAnswerResponse::_internal_mutable_warning_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  if (_impl_.warning_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::grpc::obu::msg::ObuWarningInfo>(GetArena());
    _impl_.warning_info_ = reinterpret_cast<::grpc::obu::msg::ObuWarningInfo*>(p);
  }
  return _impl_.warning_info_;
}
inline ::grpc::obu::msg::ObuWarningInfo* ObuAnswerResponse::mutable_warning_info() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::grpc::obu::msg::ObuWarningInfo* _msg = _internal_mutable_warning_info();
  // @@protoc_insertion_point(field_mutable:grpc.obu.msg.ObuAnswerResponse.warning_info)
  return _msg;
}
inline void ObuAnswerResponse::set_allocated_warning_info(::grpc::obu::msg::ObuWarningInfo* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.warning_info_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.warning_info_ = reinterpret_cast<::grpc::obu::msg::ObuWarningInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:grpc.obu.msg.ObuAnswerResponse.warning_info)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace msg
}  // namespace obu
}  // namespace grpc


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_obu_5fservice_2eproto_2epb_2eh
