// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obu_service.proto

#include "obu_service.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace grpc {
namespace obu {
namespace msg {

inline constexpr ObuAnswerRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : api_version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ObuAnswerRequest::ObuAnswerRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ObuAnswerRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ObuAnswerRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ObuAnswerRequestDefaultTypeInternal() {}
  union {
    ObuAnswerRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ObuAnswerRequestDefaultTypeInternal _ObuAnswerRequest_default_instance_;

inline constexpr ObuAnswerResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        api_version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        basic_info_{nullptr},
        traffic_light_info_{nullptr},
        warning_info_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ObuAnswerResponse::ObuAnswerResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ObuAnswerResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ObuAnswerResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ObuAnswerResponseDefaultTypeInternal() {}
  union {
    ObuAnswerResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ObuAnswerResponseDefaultTypeInternal _ObuAnswerResponse_default_instance_;
}  // namespace msg
}  // namespace obu
}  // namespace grpc
static ::_pb::Metadata file_level_metadata_obu_5fservice_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_obu_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_obu_5fservice_2eproto = nullptr;
const ::uint32_t TableStruct_obu_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::grpc::obu::msg::ObuAnswerRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::grpc::obu::msg::ObuAnswerRequest, _impl_.api_version_),
    PROTOBUF_FIELD_OFFSET(::grpc::obu::msg::ObuAnswerResponse, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::grpc::obu::msg::ObuAnswerResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::grpc::obu::msg::ObuAnswerResponse, _impl_.api_version_),
    PROTOBUF_FIELD_OFFSET(::grpc::obu::msg::ObuAnswerResponse, _impl_.basic_info_),
    PROTOBUF_FIELD_OFFSET(::grpc::obu::msg::ObuAnswerResponse, _impl_.traffic_light_info_),
    PROTOBUF_FIELD_OFFSET(::grpc::obu::msg::ObuAnswerResponse, _impl_.warning_info_),
    ~0u,
    0,
    1,
    2,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::grpc::obu::msg::ObuAnswerRequest)},
        {9, 21, -1, sizeof(::grpc::obu::msg::ObuAnswerResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::grpc::obu::msg::_ObuAnswerRequest_default_instance_._instance,
    &::grpc::obu::msg::_ObuAnswerResponse_default_instance_._instance,
};
const char descriptor_table_protodef_obu_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\021obu_service.proto\022\014grpc.obu.msg\032\021obu_m"
    "essage.proto\"\'\n\020ObuAnswerRequest\022\023\n\013api_"
    "version\030\001 \001(\t\"\313\001\n\021ObuAnswerResponse\022\023\n\013a"
    "pi_version\030\001 \001(\t\022.\n\nbasic_info\030\002 \001(\0132\032.g"
    "rpc.obu.msg.ObuBasicInfo\022=\n\022traffic_ligh"
    "t_info\030\003 \001(\0132!.grpc.obu.msg.ObuTrafficLi"
    "ghtInfo\0222\n\014warning_info\030\004 \001(\0132\034.grpc.obu"
    ".msg.ObuWarningInfo2_\n\nObuService\022Q\n\014ans"
    "werMethod\022\036.grpc.obu.msg.ObuAnswerReques"
    "t\032\037.grpc.obu.msg.ObuAnswerResponse\"\000b\006pr"
    "oto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_obu_5fservice_2eproto_deps[1] =
    {
        &::descriptor_table_obu_5fmessage_2eproto,
};
static ::absl::once_flag descriptor_table_obu_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_obu_5fservice_2eproto = {
    false,
    false,
    404,
    descriptor_table_protodef_obu_5fservice_2eproto,
    "obu_service.proto",
    &descriptor_table_obu_5fservice_2eproto_once,
    descriptor_table_obu_5fservice_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_obu_5fservice_2eproto::offsets,
    file_level_metadata_obu_5fservice_2eproto,
    file_level_enum_descriptors_obu_5fservice_2eproto,
    file_level_service_descriptors_obu_5fservice_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_obu_5fservice_2eproto_getter() {
  return &descriptor_table_obu_5fservice_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_obu_5fservice_2eproto(&descriptor_table_obu_5fservice_2eproto);
namespace grpc {
namespace obu {
namespace msg {
// ===================================================================

class ObuAnswerRequest::_Internal {
 public:
};

ObuAnswerRequest::ObuAnswerRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:grpc.obu.msg.ObuAnswerRequest)
}
inline PROTOBUF_NDEBUG_INLINE ObuAnswerRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : api_version_(arena, from.api_version_),
        _cached_size_{0} {}

ObuAnswerRequest::ObuAnswerRequest(
    ::google::protobuf::Arena* arena,
    const ObuAnswerRequest& from)
    : ::google::protobuf::Message(arena) {
  ObuAnswerRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:grpc.obu.msg.ObuAnswerRequest)
}
inline PROTOBUF_NDEBUG_INLINE ObuAnswerRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : api_version_(arena),
        _cached_size_{0} {}

inline void ObuAnswerRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ObuAnswerRequest::~ObuAnswerRequest() {
  // @@protoc_insertion_point(destructor:grpc.obu.msg.ObuAnswerRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ObuAnswerRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.api_version_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ObuAnswerRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:grpc.obu.msg.ObuAnswerRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.api_version_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ObuAnswerRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 49, 2> ObuAnswerRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ObuAnswerRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string api_version = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ObuAnswerRequest, _impl_.api_version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string api_version = 1;
    {PROTOBUF_FIELD_OFFSET(ObuAnswerRequest, _impl_.api_version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\35\13\0\0\0\0\0\0"
    "grpc.obu.msg.ObuAnswerRequest"
    "api_version"
  }},
};

::uint8_t* ObuAnswerRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:grpc.obu.msg.ObuAnswerRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string api_version = 1;
  if (!this->_internal_api_version().empty()) {
    const std::string& _s = this->_internal_api_version();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "grpc.obu.msg.ObuAnswerRequest.api_version");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:grpc.obu.msg.ObuAnswerRequest)
  return target;
}

::size_t ObuAnswerRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:grpc.obu.msg.ObuAnswerRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string api_version = 1;
  if (!this->_internal_api_version().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_api_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ObuAnswerRequest::_class_data_ = {
    ObuAnswerRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ObuAnswerRequest::GetClassData() const {
  return &_class_data_;
}

void ObuAnswerRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ObuAnswerRequest*>(&to_msg);
  auto& from = static_cast<const ObuAnswerRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:grpc.obu.msg.ObuAnswerRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_api_version().empty()) {
    _this->_internal_set_api_version(from._internal_api_version());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ObuAnswerRequest::CopyFrom(const ObuAnswerRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:grpc.obu.msg.ObuAnswerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ObuAnswerRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ObuAnswerRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ObuAnswerRequest::InternalSwap(ObuAnswerRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.api_version_, &other->_impl_.api_version_, arena);
}

::google::protobuf::Metadata ObuAnswerRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_obu_5fservice_2eproto_getter, &descriptor_table_obu_5fservice_2eproto_once,
      file_level_metadata_obu_5fservice_2eproto[0]);
}
// ===================================================================

class ObuAnswerResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<ObuAnswerResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ObuAnswerResponse, _impl_._has_bits_);
  static const ::grpc::obu::msg::ObuBasicInfo& basic_info(const ObuAnswerResponse* msg);
  static void set_has_basic_info(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::grpc::obu::msg::ObuTrafficLightInfo& traffic_light_info(const ObuAnswerResponse* msg);
  static void set_has_traffic_light_info(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::grpc::obu::msg::ObuWarningInfo& warning_info(const ObuAnswerResponse* msg);
  static void set_has_warning_info(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::grpc::obu::msg::ObuBasicInfo& ObuAnswerResponse::_Internal::basic_info(const ObuAnswerResponse* msg) {
  return *msg->_impl_.basic_info_;
}
const ::grpc::obu::msg::ObuTrafficLightInfo& ObuAnswerResponse::_Internal::traffic_light_info(const ObuAnswerResponse* msg) {
  return *msg->_impl_.traffic_light_info_;
}
const ::grpc::obu::msg::ObuWarningInfo& ObuAnswerResponse::_Internal::warning_info(const ObuAnswerResponse* msg) {
  return *msg->_impl_.warning_info_;
}
void ObuAnswerResponse::clear_basic_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.basic_info_ != nullptr) _impl_.basic_info_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void ObuAnswerResponse::clear_traffic_light_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.traffic_light_info_ != nullptr) _impl_.traffic_light_info_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void ObuAnswerResponse::clear_warning_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.warning_info_ != nullptr) _impl_.warning_info_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
ObuAnswerResponse::ObuAnswerResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:grpc.obu.msg.ObuAnswerResponse)
}
inline PROTOBUF_NDEBUG_INLINE ObuAnswerResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        api_version_(arena, from.api_version_) {}

ObuAnswerResponse::ObuAnswerResponse(
    ::google::protobuf::Arena* arena,
    const ObuAnswerResponse& from)
    : ::google::protobuf::Message(arena) {
  ObuAnswerResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.basic_info_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::grpc::obu::msg::ObuBasicInfo>(arena, *from._impl_.basic_info_)
                : nullptr;
  _impl_.traffic_light_info_ = (cached_has_bits & 0x00000002u)
                ? CreateMaybeMessage<::grpc::obu::msg::ObuTrafficLightInfo>(arena, *from._impl_.traffic_light_info_)
                : nullptr;
  _impl_.warning_info_ = (cached_has_bits & 0x00000004u)
                ? CreateMaybeMessage<::grpc::obu::msg::ObuWarningInfo>(arena, *from._impl_.warning_info_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:grpc.obu.msg.ObuAnswerResponse)
}
inline PROTOBUF_NDEBUG_INLINE ObuAnswerResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        api_version_(arena) {}

inline void ObuAnswerResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, basic_info_),
           0,
           offsetof(Impl_, warning_info_) -
               offsetof(Impl_, basic_info_) +
               sizeof(Impl_::warning_info_));
}
ObuAnswerResponse::~ObuAnswerResponse() {
  // @@protoc_insertion_point(destructor:grpc.obu.msg.ObuAnswerResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ObuAnswerResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.api_version_.Destroy();
  delete _impl_.basic_info_;
  delete _impl_.traffic_light_info_;
  delete _impl_.warning_info_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ObuAnswerResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:grpc.obu.msg.ObuAnswerResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.api_version_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.basic_info_ != nullptr);
      _impl_.basic_info_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.traffic_light_info_ != nullptr);
      _impl_.traffic_light_info_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.warning_info_ != nullptr);
      _impl_.warning_info_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ObuAnswerResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 3, 50, 2> ObuAnswerResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ObuAnswerResponse, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ObuAnswerResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .grpc.obu.msg.ObuWarningInfo warning_info = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 2, 2, PROTOBUF_FIELD_OFFSET(ObuAnswerResponse, _impl_.warning_info_)}},
    // string api_version = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ObuAnswerResponse, _impl_.api_version_)}},
    // .grpc.obu.msg.ObuBasicInfo basic_info = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(ObuAnswerResponse, _impl_.basic_info_)}},
    // .grpc.obu.msg.ObuTrafficLightInfo traffic_light_info = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(ObuAnswerResponse, _impl_.traffic_light_info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string api_version = 1;
    {PROTOBUF_FIELD_OFFSET(ObuAnswerResponse, _impl_.api_version_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .grpc.obu.msg.ObuBasicInfo basic_info = 2;
    {PROTOBUF_FIELD_OFFSET(ObuAnswerResponse, _impl_.basic_info_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .grpc.obu.msg.ObuTrafficLightInfo traffic_light_info = 3;
    {PROTOBUF_FIELD_OFFSET(ObuAnswerResponse, _impl_.traffic_light_info_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .grpc.obu.msg.ObuWarningInfo warning_info = 4;
    {PROTOBUF_FIELD_OFFSET(ObuAnswerResponse, _impl_.warning_info_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::grpc::obu::msg::ObuBasicInfo>()},
    {::_pbi::TcParser::GetTable<::grpc::obu::msg::ObuTrafficLightInfo>()},
    {::_pbi::TcParser::GetTable<::grpc::obu::msg::ObuWarningInfo>()},
  }}, {{
    "\36\13\0\0\0\0\0\0"
    "grpc.obu.msg.ObuAnswerResponse"
    "api_version"
  }},
};

::uint8_t* ObuAnswerResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:grpc.obu.msg.ObuAnswerResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string api_version = 1;
  if (!this->_internal_api_version().empty()) {
    const std::string& _s = this->_internal_api_version();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "grpc.obu.msg.ObuAnswerResponse.api_version");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .grpc.obu.msg.ObuBasicInfo basic_info = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, _Internal::basic_info(this),
        _Internal::basic_info(this).GetCachedSize(), target, stream);
  }

  // .grpc.obu.msg.ObuTrafficLightInfo traffic_light_info = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, _Internal::traffic_light_info(this),
        _Internal::traffic_light_info(this).GetCachedSize(), target, stream);
  }

  // .grpc.obu.msg.ObuWarningInfo warning_info = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, _Internal::warning_info(this),
        _Internal::warning_info(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:grpc.obu.msg.ObuAnswerResponse)
  return target;
}

::size_t ObuAnswerResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:grpc.obu.msg.ObuAnswerResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string api_version = 1;
  if (!this->_internal_api_version().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_api_version());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // .grpc.obu.msg.ObuBasicInfo basic_info = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.basic_info_);
    }

    // .grpc.obu.msg.ObuTrafficLightInfo traffic_light_info = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.traffic_light_info_);
    }

    // .grpc.obu.msg.ObuWarningInfo warning_info = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.warning_info_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ObuAnswerResponse::_class_data_ = {
    ObuAnswerResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ObuAnswerResponse::GetClassData() const {
  return &_class_data_;
}

void ObuAnswerResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ObuAnswerResponse*>(&to_msg);
  auto& from = static_cast<const ObuAnswerResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:grpc.obu.msg.ObuAnswerResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_api_version().empty()) {
    _this->_internal_set_api_version(from._internal_api_version());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_basic_info()->::grpc::obu::msg::ObuBasicInfo::MergeFrom(
          from._internal_basic_info());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_traffic_light_info()->::grpc::obu::msg::ObuTrafficLightInfo::MergeFrom(
          from._internal_traffic_light_info());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_warning_info()->::grpc::obu::msg::ObuWarningInfo::MergeFrom(
          from._internal_warning_info());
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ObuAnswerResponse::CopyFrom(const ObuAnswerResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:grpc.obu.msg.ObuAnswerResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ObuAnswerResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ObuAnswerResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ObuAnswerResponse::InternalSwap(ObuAnswerResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.api_version_, &other->_impl_.api_version_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ObuAnswerResponse, _impl_.warning_info_)
      + sizeof(ObuAnswerResponse::_impl_.warning_info_)
      - PROTOBUF_FIELD_OFFSET(ObuAnswerResponse, _impl_.basic_info_)>(
          reinterpret_cast<char*>(&_impl_.basic_info_),
          reinterpret_cast<char*>(&other->_impl_.basic_info_));
}

::google::protobuf::Metadata ObuAnswerResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_obu_5fservice_2eproto_getter, &descriptor_table_obu_5fservice_2eproto_once,
      file_level_metadata_obu_5fservice_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace msg
}  // namespace obu
}  // namespace grpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
