// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: obu_service.proto
#ifndef GRPC_obu_5fservice_2eproto__INCLUDED
#define GRPC_obu_5fservice_2eproto__INCLUDED

#include "obu_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace grpc {
namespace obu {
namespace msg {

class ObuService final {
 public:
  static constexpr char const* service_full_name() {
    return "grpc.obu.msg.ObuService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status answerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::obu::msg::ObuAnswerResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc::obu::msg::ObuAnswerResponse>> AsyncanswerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc::obu::msg::ObuAnswerResponse>>(AsyncanswerMethodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc::obu::msg::ObuAnswerResponse>> PrepareAsyncanswerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc::obu::msg::ObuAnswerResponse>>(PrepareAsyncanswerMethodRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void answerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest* request, ::grpc::obu::msg::ObuAnswerResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void answerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest* request, ::grpc::obu::msg::ObuAnswerResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc::obu::msg::ObuAnswerResponse>* AsyncanswerMethodRaw(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc::obu::msg::ObuAnswerResponse>* PrepareAsyncanswerMethodRaw(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status answerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::obu::msg::ObuAnswerResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc::obu::msg::ObuAnswerResponse>> AsyncanswerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc::obu::msg::ObuAnswerResponse>>(AsyncanswerMethodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc::obu::msg::ObuAnswerResponse>> PrepareAsyncanswerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc::obu::msg::ObuAnswerResponse>>(PrepareAsyncanswerMethodRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void answerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest* request, ::grpc::obu::msg::ObuAnswerResponse* response, std::function<void(::grpc::Status)>) override;
      void answerMethod(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest* request, ::grpc::obu::msg::ObuAnswerResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpc::obu::msg::ObuAnswerResponse>* AsyncanswerMethodRaw(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpc::obu::msg::ObuAnswerResponse>* PrepareAsyncanswerMethodRaw(::grpc::ClientContext* context, const ::grpc::obu::msg::ObuAnswerRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_answerMethod_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status answerMethod(::grpc::ServerContext* context, const ::grpc::obu::msg::ObuAnswerRequest* request, ::grpc::obu::msg::ObuAnswerResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_answerMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_answerMethod() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_answerMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status answerMethod(::grpc::ServerContext* /*context*/, const ::grpc::obu::msg::ObuAnswerRequest* /*request*/, ::grpc::obu::msg::ObuAnswerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestanswerMethod(::grpc::ServerContext* context, ::grpc::obu::msg::ObuAnswerRequest* request, ::grpc::ServerAsyncResponseWriter< ::grpc::obu::msg::ObuAnswerResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_answerMethod<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_answerMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_answerMethod() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::obu::msg::ObuAnswerRequest, ::grpc::obu::msg::ObuAnswerResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::obu::msg::ObuAnswerRequest* request, ::grpc::obu::msg::ObuAnswerResponse* response) { return this->answerMethod(context, request, response); }));}
    void SetMessageAllocatorFor_answerMethod(
        ::grpc::MessageAllocator< ::grpc::obu::msg::ObuAnswerRequest, ::grpc::obu::msg::ObuAnswerResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpc::obu::msg::ObuAnswerRequest, ::grpc::obu::msg::ObuAnswerResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_answerMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status answerMethod(::grpc::ServerContext* /*context*/, const ::grpc::obu::msg::ObuAnswerRequest* /*request*/, ::grpc::obu::msg::ObuAnswerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* answerMethod(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::obu::msg::ObuAnswerRequest* /*request*/, ::grpc::obu::msg::ObuAnswerResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_answerMethod<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_answerMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_answerMethod() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_answerMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status answerMethod(::grpc::ServerContext* /*context*/, const ::grpc::obu::msg::ObuAnswerRequest* /*request*/, ::grpc::obu::msg::ObuAnswerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_answerMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_answerMethod() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_answerMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status answerMethod(::grpc::ServerContext* /*context*/, const ::grpc::obu::msg::ObuAnswerRequest* /*request*/, ::grpc::obu::msg::ObuAnswerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestanswerMethod(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_answerMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_answerMethod() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->answerMethod(context, request, response); }));
    }
    ~WithRawCallbackMethod_answerMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status answerMethod(::grpc::ServerContext* /*context*/, const ::grpc::obu::msg::ObuAnswerRequest* /*request*/, ::grpc::obu::msg::ObuAnswerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* answerMethod(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_answerMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_answerMethod() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpc::obu::msg::ObuAnswerRequest, ::grpc::obu::msg::ObuAnswerResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpc::obu::msg::ObuAnswerRequest, ::grpc::obu::msg::ObuAnswerResponse>* streamer) {
                       return this->StreamedanswerMethod(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_answerMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status answerMethod(::grpc::ServerContext* /*context*/, const ::grpc::obu::msg::ObuAnswerRequest* /*request*/, ::grpc::obu::msg::ObuAnswerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedanswerMethod(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpc::obu::msg::ObuAnswerRequest,::grpc::obu::msg::ObuAnswerResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_answerMethod<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_answerMethod<Service > StreamedService;
};

}  // namespace msg
}  // namespace obu
}  // namespace grpc


#endif  // GRPC_obu_5fservice_2eproto__INCLUDED
